### ISSUE TITLE
Update to be buildable with Nightly or Stable rust

### ISSUE THREAD

**Issue by jrmuizel** [fitzgen/bacon-rajan-cc#3]
It seems like this crate is providing useful functionality. It would be nice to make it usable again.

**Comment by fitzgen** [comment]
This crate never got fully usable.

At minimum, it needs to have its own fork of RefCell that it can see inside of regardless of borrow status so that it can trace the thing's edges. There are probably a lot more issues than just that, but that's what I remember.

Happy to give collaboratorship / co-ownership if you want to finish this!

**Comment by jrmuizel** [comment]
Yeah, I'm some what interested. I got it building here: https://github.com/jrmuizel/bacon-rajan-cc/tree/nightly. I'll try to get it split up into more reviewable chunks and post PRs.

**Comment by fitzgen** [comment]
If cycle collection kicks in while a refcell is borrowed, it may need to trace through the refcell, but that will assert since it is already borrowed. Need a version that allows tracing regardless whether it is borrowed.

**Comment by jrmuizel** [comment]
I don't think it's safe to trace through the RefCell if it's already borrowed. A Drop implementation could mutate it during cycle collection which will break tracing.

In rust-gc GcCell roots the value in borrow_mut():
https://github.com/Manishearth/rust-gc/blob/e362a0687260534305b2749f986da3f0df1ec356/gc/src/lib.rs#L446

and won't trace through GcCell if it's borrowed:
https://github.com/Manishearth/rust-gc/blob/e362a0687260534305b2749f986da3f0df1ec356/gc/src/lib.rs#L464

**Comment by jrmuizel** [comment]
This is done now.
